In [1]:
import numpy as np
import pandas as pd

In [11]:
M = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
U = np.matrix([[5,5,5]])
V = np.matrix(np.random.rand(3, 1))

In [12]:
print M, U, V

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[5 5 5]] [[ 0.55104227]
 [ 0.49232825]
 [ 0.08017982]]


In [19]:
def gradient_descent(M, U, V, alpha, num_iters):
    for i in range(num_iters):
        diff = (V * U) - M
        V = V - alpha * (diff*U.T)
    return V

In [20]:
V = gradient_descent(M, U, V, 0.01, 1000)

In [21]:
print V

[[ 0.4]
 [ 1. ]
 [ 1.6]]
